name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    env:
      RUN_ANALYZE: ${{ github.event.pull_request.user.login != 'dependabot' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          FETCH_DEPTH: ${{ env.RUN_ANALYZE == 'true' && '0' || '1' }}
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Cache SonarCloud packages
        if: ${{ env.RUN_ANALYZE == 'true' }}
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build
        env:
          IO_GITHUB_NSTDIO_HTTP_EXT_CLIENT_TEST_CACHE_WRITE_DELAY: PT2.5S
        run: ./gradlew build --stacktrace --scan
      - name: Analyze
        if: ${{ env.RUN_ANALYZE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube
