name: Build
on:
  push:
    branches:
      - main
      - 2.x
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Build
        env:
          IO_GITHUB_NSTDIO_HTTP_EXT_CLIENT_TEST_CACHE_WRITE_DELAY: PT4.5S
        run: ./gradlew build --scan
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "build/test-results/**/*.xml"
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
